### ISSUE TITLE
require from nodejs and webpack are not similar

### ISSUE THREAD

**Issue by Tyrame** [redux-utilities/reduce-reducers#22]
Consider the following code:
```
var reduceReducers = require('reduce-reducers');
console.log(reduceReducers.default);
```

Running this code in node.js with `node index.js`, the output is `undefined`.

When processed with webpack with the following configuration:
```
module.exports = {
    mode: 'development',
    entry: {
        index: './index.js'
    },
    output: {
        filename: 'index.js'
    }
};
```
And executed in node.js with `node dist/index.js`, then the output is `[Function]`.

In the file `lib/index.js`, replacing `module.exports = exports['default']` with `module.exports = exports` makes the whole thing work.

Am I missing something?

**Comment by Tyrame** [comment]
It is an expected behaviour from babel.
However, there is an option in the tool to add the default property in module.exports to restore compatibility between ES modules and CJS exports.

I made a PR: #23.

**Comment by timche** [comment]
Why would you use `require` with `reduceReducers.default` instead of just `reduceReducers`?

**Comment by Tyrame** [comment]
In my use case, I want to execute the same bunch of code in the browser, and in node.js.
The library using it uses typescript, and imports reduce-reducers like this:
```
import reduceReducers from 'reduce-reducers';
reduceReducers(...);
```
which transpiles to:
```
var reduce_reducers_1 = require("reduce-reducers");
reduce_reducers_1.default(...);
```

**Comment by timche** [comment]
Wouldn't it be possible if would use `import` instead? It will be transpiled any before executing IIRC.

**Comment by Tyrame** [comment]
I am not sure to understand what your suggestion is. Where would the `import` be used ?

**Comment by timche** [comment]
So instead of this

```js
var reduceReducers = require('reduce-reducers');
```

you would do this:

```js
import reduceReducers from 'reduce-reducers`;
console.log(reducerReducers)
```

**Comment by Tyrame** [comment]
The library I want to run on the browser and node.js is written in typescript and is pretty large (> 20k lines of code), so I cannot really change this...

**Comment by timche** [comment]
I get it, but I won't do this change just for you, because how the this library is exported as CommonJS is correct.

TypeScript is using `import` and `export` by design, so you should definitely change from `require` to `import`: https://www.typescriptlang.org/docs/handbook/modules.html

> Modules are executed within their own scope, not in the global scope; this means that variables, functions, classes, etc. declared in a module are not visible outside the module unless they are explicitly exported using one of the export forms. Conversely, to consume a variable, function, class, interface, etc. exported from a different module, it has to be imported using one of the import forms.

**Comment by timche** [comment]
Can you please share your `tsconfig.json`?

**Comment by Tyrame** [comment]
```
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es5",
        "sourceMap": true,
        "jsx": "react",
        "experimentalDecorators": true,
        "outDir": "lib",
        "declaration": true,
        "pretty": true,
        "lib": ["es2015", "dom"]
    },
    "include": ["src"]
}
```

**Comment by timche** [comment]
And how do you import `reduce-reducers`? Can you share an example source code snippet?

**Comment by timche** [comment]
Okay, so actually it must be:
```ts
import * as reduceReducers from 'reduce-reducers';
```

Can you try this please?

Unless you have set `"allowSyntheticDefaultImports": true" in `tsconfig.json`, but I can't see it.

**Comment by Tyrame** [comment]
I tried this:
```javascript
import * as reduceReducers from 'reduce-reducers';
import reduceReducers2 from 'reduce-reducers';

console.log('reduceReducers', reduceReducers);
console.log('reduceReducers2', reduceReducers2);
```

which once transpiled gives:
```javascript
var reduceReducers = require("reduce-reducers");
var reduce_reducers_1 = require("reduce-reducers");

console.log('reduceReducers:', reduceReducers);
console.log('reduceReducers2:', reduce_reducers_1.default);
```

When running the code on node.js, I get the output:
```
reduceReducers: function () ...
reduceReducers2: undefined
```

and when running on the browser after bundling with webpack:
```
reduceReducers: { default: function() ... }
reduceReducers2: function() ...
```

**Comment by timche** [comment]
When transpiling for Node.js, can you please try using `--esModuleInterop true` on the CLI?

**Comment by Tyrame** [comment]
Looks like it solves my problem. I have the same format on both sides now. I did not know this option as the project exists since typescript 1 and this was added with typescript 2.7.
Thanks for your help !
