### ISSUE TITLE
Consider to change API

### ISSUE THREAD

**Issue by RumyantsevMichael** [redux-utilities/reduce-reducers#25]
It'll be better to provide the initialState as the first argument. Otherwise it's impossible to declare proper typings (both for Typescript and Flow), cause rest parameters (list of reducers in the case) must be at the end of parameters list.

**Comment by timche** [comment]
Normally I'd have added `initialState` as first parameter, but it was added with compatibility in mind without having breaking changes. I'm open to release a new major version with `initialState` as first parameter and typing support.

**Comment by RumyantsevMichael** [comment]
I've created a PR (#27)

**Comment by timche** [comment]
Released in [`v1.0.0`](https://github.com/redux-utilities/reduce-reducers/releases/tag/v1.0.0)
