### ISSUE TITLE
Is this package the same as combineReducers?

### ISSUE THREAD

**Issue by joetidee** [redux-utilities/reduce-reducers#8]
Could you tell me if this package is the same as using the `combineReducers` function form the `redux` package? If not, would you mind explaining the difference?

**Comment by davidnum** [comment]
Hi! This package for updating dependent state across different branches of the state tree.

**Comment by chellberg** [comment]
I was directed here by discussion mentioning this as a tool for updating dependent state across different branches of the state tree, and after staring at the code sample in the README I figured out what this is doing, but I agree that it's not very clear from the description.

>Originally created to **combine multiple Redux reducers** that correspond to different actions 

sounds a lot like `combineReducers`, and "correspond to different actions" doesn't do much to clarify things. It'd be great if "dependent state" was somewhere in the readme.

**Comment by AJamesPhillips** [comment]
@chellberg you could open a pull request with updates to the readme :)

**Comment by sohaibfarooqi** [comment]
This [SO](https://stackoverflow.com/a/44371190/5741172) also explains the difference between `combineReducer` and `reduceReducer`

**Comment by avremel** [comment]
To understand how exactly this function works:
https://stackoverflow.com/questions/48104778/how-does-reducereducers-work

**Comment by timche** [comment]
Seems to be answered, so I'm closing this.
